"""Constants for pi assistant component"""

ATTR_CABLE_ATTACHED = "cableAttached"
ATTR_PLUG_TYPE_NAME = "plugTypeName"
ATTR_MAX_POWER_IN_KW = "maxPowerInKw"
ATTR_MAX_POWER_PER_PLUG_TYPE_IN_KW = "maxPowerInKwPerPlugType"
ATTR_EVSE_ID = "evseId"
ATTR_ADDRESS = "address"
ATTR_UPDATED_AT = "updatedAt"
ATTR_AVAILABLE_CHARGE_POINTS = "availableChargePoints"
ATTR_TOTAL_CHARGE_POINTS = "totalChargePoints"
DOMAIN = "enbw_chargestations"
STATION_NUMBER = "station_number"
NAME = "name"
LATITUDE = "latitude"
LONGITUDE = "longitude"
SEARCH_RADIUS = "search_radius"
API_KEY = "api_key"
DEG_PER_KM = 1 / 111
